services:
  web:
    image: ghcr.io/motocru/kevinu-web:latest
    container_name: kevinu-web
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
    restart: unless-stopped
  db:
    image: mysql:8.0
    container_name: kevinu-db
    env_file:
      - ./.env
    volumes:
      - kevinu-db-data:/var/lib/mysql
      - ./server/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  nginx:
    image: nginx:latest
    container_name: kevinu-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - web
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: kevinu-certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  kevinu-db-data:
